import Head from 'next/head';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';

import Body from '../components/body/Body';
import Header from '../components/header/Header';
import Main from '../components/main/Main';
import Footer from '../components/footer/Footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Body>
        <Header>Header section</Header>
        <Main>Main section</Main>
        <Footer>Footer section</Footer>
      </Body>
    </div>
  );
}
