import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Body from '../components/body/Body';
import Main from '../components/main/Main';
import Header from '../components/header/Header';
import HeroBanner from '../components/herobanner/Herobanner';
import Projects from '../components/projects/Projects';
import Philosophy from '../components/philosophy/Philosophy';
import Skill from '../components/skill/Skill';
import About from '../components/about/About';
import Contact from '../components/contact/Contact';
import Footer from '../components/footer/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Alexander Hansen Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Body>
        <Main>
          <Header />
          <HeroBanner />
          <Projects />
          <Philosophy />
          <Skill />
          <About id='about' />
          <Contact id='contact' />
          <Footer />
        </Main>
      </Body>
    </>
  );
}
